spring:
  datasource:
    url: jdbc:mysql://139.155.80.168:3306/blogs?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: blogs
    password: fu13092b9
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 139.155.80.168
    port: 6379
    password: fu13092b9
    lettuce.pool:
      max-active: 45
      max-idle: 100
      min-idle: 1
    database: 2
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  configuration:
    cache-enabled: false
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true


server:
  port: 10505

global-config:
  file-path:
    common-file: ./resources/file/
#      /root/blogs/file
    photo: /root/blogs/
    upLoad-photo: ./resources/photo/original-image/
    out-photo: ./resources/photo/finished-product-photo/

file-type:
  photo-type:
    - jpg
    - gif
    - png
    - jpeg
